name: Publish packages to PyPI

on:
  workflow_dispatch:

jobs:
  build:
    name: Build the source tarball and the wheel
    runs-on: ubuntu-latest
    timeout-minutes: 20
    env:
      SETUPTOOLS_SCM_PRETEND_VERSION: "4.12.1"
    steps:
      - uses: actions/checkout@v6
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: 3.x
      - name: Install dependencies
        run: pip install build "setuptools==80.9.0" "setuptools_scm==9.2.2"
      - name: Create packages
        run: python -m build --no-isolation
      - name: Archive packages
        uses: actions/upload-artifact@v6
        with:
          name: dist
          path: dist
          if-no-files-found: error

  publish:
    name: Publish build artifacts to the PyPI
    needs: build
    if: false
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      id-token: write
    steps:
      - name: Retrieve packages
        uses: actions/download-artifact@v7
        with:
          name: dist
          path: dist
      - name: Upload packages
        uses: pypa/gh-action-pypi-publish@release/v1

  release:
    name: Create a GitHub release
    needs: build
    if: false
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6
      - id: changelog
        uses: agronholm/release-notes@v1
        with:
          path: docs/versionhistory.rst
      - uses: ncipollo/release-action@v1
        with:
          body: ${{ steps.changelog.outputs.changelog }}
